# Generated by Django 5.2.1 on 2025-05-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(choices=[('casablanca', 'Casablanca'), ('rabat', 'Rabat'), ('marrakech', 'Marrakech'), ('fes', 'Fes'), ('tangier', 'Tangier'), ('agadir', 'Agadir'), ('meknes', 'Meknes'), ('oujda', 'Oujda'), ('kenitra', 'Kenitra'), ('tetouan', 'Tetouan'), ('safi', 'Safi'), ('mohammedia', 'Mohammedia'), ('el_jadida', 'El Jadida'), ('nador', 'Nador'), ('beni_mellal', 'Beni Mellal'), ('taza', 'Taza'), ('settat', 'Settat')], max_length=200),
        ),
    ]
