# Generated by Django 5.2.1 on 2025-05-30 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_alter_property_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='features',
        ),
    ]
